// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUtFdlyN6V3_F8uwWRl8tWrxGqoTWk1zs',
    appId: '1:84456946174:web:b77887109fb4c1b0f5a8af',
    messagingSenderId: '84456946174',
    projectId: 'maulahjatflutter',
    authDomain: 'maulahjatflutter.firebaseapp.com',
    databaseURL: 'https://maulahjatflutter-default-rtdb.firebaseio.com',
    storageBucket: 'maulahjatflutter.appspot.com',
    measurementId: 'G-0EMXX33WC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-YWIImvEYPXjBqhAZbafPPCVFghiEz3c',
    appId: '1:84456946174:android:17b428d1dc5be72af5a8af',
    messagingSenderId: '84456946174',
    projectId: 'maulahjatflutter',
    databaseURL: 'https://maulahjatflutter-default-rtdb.firebaseio.com',
    storageBucket: 'maulahjatflutter.appspot.com',
  );
}
